# Generated by Django 3.1.2 on 2020-10-27 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'Groceries'), ('health', 'Health & Beauty'), ('home', 'Home & Office'), ('phones', 'Phones & Tablets'), ('computing', 'Computing'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('baby', 'Baby Products'), ('gaming', 'Gaming'), ('sporting', 'Sporting Goods'), ('automobile', 'Automobile'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listings',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
