# Generated by Django 3.1.2 on 2020-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201030_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Health & Beauty', 'Health & Beauty'), ('Home & Office', 'Home & Office'), ('Phones & Tablets', 'Phones & Tablets'), ('Computing', 'Computing'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Baby Products', 'Baby Products'), ('Gaming', 'Gaming'), ('Sporting Goods', 'Sporting Goods'), ('Automobile', 'Automobile'), ('Other', 'Other')], max_length=50),
        ),
    ]
